### ISSUE TITLE
&mut is not valid in ffi functions

### ISSUE THREAD

**Issue by Dr-Emann** [greyblake/whatlang-ffi#1]
Rust `&mut` references have more guarantees than do c pointers: non-nullabilty and uniqueness. FFI functions should therefore avoid use of them as arguments, as c callers could pass null, or a non-unique pointer.

https://github.com/greyblake/whatlang-ffi/blob/54e9a1d4f43dbb359798b42c61cff6c2e6360eac/src/lib.rs#L17

**Comment by iwillspeak** [comment]
This is actually fixed by #8 and can be closed now. I must have messed up the mention in that PR so it hasn't been auto-closed.
